### ISSUE TITLE
Retrieving array element that was out of bounds

### ISSUE THREAD

**Issue by TimHeessels** [V0odo0/KNOT-Localization#1]
First off, I love this plugin, thanks so much for making it.

There seems to be an issue with the arrays of the metadata on first loading of the database editor. Don't know if it's something you can reproduce or that i've done something wrong.

```
Retrieving array element that was out of bounds
UnityEditor.SerializedProperty:GetArrayElementAtIndex (int)
Knot.Localization.Editor.KnotMetadataReorderableList:GetElementHeight (int) (at Library/PackageCache/com.knot.localization@70fd9f3081/Editor/Scripts/UI/KnotMetadataReorderableList.cs:62)
UnityEditorInternal.ReorderableList:CacheIfNeeded ()
UnityEditorInternal.ReorderableList:GetListElementHeight ()
UnityEditorInternal.ReorderableList:DoLayoutList ()
Knot.Localization.Editor.KnotMetadataReorderableList:DoLayoutList () (at Library/PackageCache/com.knot.localization@70fd9f3081/Editor/Scripts/UI/KnotMetadataReorderableList.cs:124)
Knot.Localization.Editor.KnotMetadataContainerEditor:<.ctor>b__10_0 () (at Library/PackageCache/com.knot.localization@70fd9f3081/Editor/Scripts/UI/KnotMetadataContainerEditor.cs:41)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
```

And

```
NullReferenceException: Object reference not set to an instance of an object
UnityEditor.PropertyHandler.GetHeight (UnityEditor.SerializedProperty property, UnityEngine.GUIContent label, System.Boolean includeChildren) (at <3371b3e2e5754acd87e600e068350da5>:0)
UnityEditor.EditorGUI.GetPropertyHeightInternal (UnityEditor.SerializedProperty property, UnityEngine.GUIContent label, System.Boolean includeChildren) (at <3371b3e2e5754acd87e600e068350da5>:0)
UnityEditor.EditorGUI.GetPropertyHeight (UnityEditor.SerializedProperty property, UnityEngine.GUIContent label, System.Boolean includeChildren) (at <3371b3e2e5754acd87e600e068350da5>:0)
UnityEditor.EditorGUI.GetPropertyHeight (UnityEditor.SerializedProperty property) (at <3371b3e2e5754acd87e600e068350da5>:0)
Knot.Localization.Editor.KnotMetadataReorderableList.GetElementHeight (System.Int32 elementIndex) (at Library/PackageCache/com.knot.localization@70fd9f3081/Editor/Scripts/UI/KnotMetadataReorderableList.cs:62)
UnityEditorInternal.ReorderableList.CacheIfNeeded () (at <3371b3e2e5754acd87e600e068350da5>:0)
UnityEditorInternal.ReorderableList.GetListElementHeight () (at <3371b3e2e5754acd87e600e068350da5>:0)
UnityEditorInternal.ReorderableList.DoLayoutList () (at <3371b3e2e5754acd87e600e068350da5>:0)
Knot.Localization.Editor.KnotMetadataReorderableList.DoLayoutList () (at Library/PackageCache/com.knot.localization@70fd9f3081/Editor/Scripts/UI/KnotMetadataReorderableList.cs:124)
Knot.Localization.Editor.KnotMetadataContainerEditor.<.ctor>b__10_0 () (at Library/PackageCache/com.knot.localization@70fd9f3081/Editor/Scripts/UI/KnotMetadataContainerEditor.cs:41)
UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <f79d3e63281a46a1a061d66eff76f483>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)
```

**Comment by V0odo0** [comment]
I can't reproduce your issue. Might be Unity version related since `ReorderableList:GetListElementHeight` usually should not be called for out of bounds array elements.

1. Which version of Unity are you using?
2. When exactly does the exception occurs? Opening database editor, switching tab, modifying metadata list etc.

**Comment by TimHeessels** [comment]
I'm using 2020.3.33f1,
The issue occurs when first opening the database and/or switching to a tab that has a metadata list. Switching back and forth after doesn't cause the issue. I've noticed the metadata array also has some delay before appearing the first time. (Modifying the list doesn't cause the errors, it's just the first time the list is shown)
It also seems to occur when entering or exiting playmode.
I'm also using Odin inspector, might have something to do with it?

![image](https://user-images.githubusercontent.com/16555855/165081816-b83d96c7-f47d-497f-9642-d3fbbec7aa18.png)

**Comment by V0odo0** [comment]
Still not reproducible for me in 2020.3.33f1 with Odin installed.

You can:
1. Check on a fresh project.
2. Step-by-step remove third party assets and packages that have Editor-related code.
3. Share your Odin inspector settings and list of installed packages from `YourProjectFolder\Packages\manifest.json`
![image](https://user-images.githubusercontent.com/10213769/165088843-9a4f7d68-1c32-4b6c-83ac-34db4ae7d045.png)

**Comment by TimHeessels** [comment]
Fresh project on 2020.3.33f1 (same version as my current project for which I send the bug), only imported the plugin (via github link to add as package). Set english as a language and switched to the text tab. Same errors.

However, I also tried on a fresh project in 2020.3.23f1 with the same setup and that didn't gave errors. 

I could try to reinstall the version of unity that gives the error since the error seems to occur on a fresh project for me, but not for you?

**Comment by V0odo0** [comment]
> Fresh project on 2020.3.33f1 (same version as my current project for which I send the bug), only imported the plugin (via github link to add as package). Set english as a language and switched to the text tab. Same errors.
> 
> However, I also tried on a fresh project in 2020.3.23f1 with the same setup and that didn't gave errors.
> 
> I could try to reinstall the version of unity that gives the error since the error seems to occur on a fresh project for me, but not for you?

Does reinstalling Unity have solved the issue?

**Comment by TimHeessels** [comment]
Nope, tried a clean install of 2020.3.33f1, same issues (By pulling the plugin via the package manager using GIT). Also tested with just downloading the project and importing the files manually.
Very weird bug, but I think it's on my end, since you haven't got the issue.

**Comment by TimHeessels** [comment]
Still not sure how. But updating to 2020.3.35f resolved the issue for me.
