### ISSUE TITLE
Can it support loading the corresponding database in the editor (not at runtime)?

### ISSUE THREAD

**Issue by mrkyee** [V0odo0/KNOT-Localization#2]
Can it support loading the corresponding database in the editor (not at runtime)? My specific case is that I want to support changing the currently effective language in real-time by modifying the passed-in index on the inspect panel during the editor period. However, I found that if KnotLocalization.Manager.Languages is empty if it's not during runtime

**Comment by mrkyee** [comment]
This way, I don't have to run the program every time, then click to switch languages, and then jump to the corresponding scene to see the effect of the switch. Instead, I can directly modify it on the inspect panel without running the program.

**Comment by V0odo0** [comment]
In runtime, components gets localized values from Manager class. It is is initialzied only in Runtime/Play Mode because it compounds raw data and might perform async operations. So it would be tricky to initialize it in Edit time every time you made a change in your Database.

```C#
/// <summary>
/// A shortcut for <see cref="IKnotManager.GetTextValue"/>. Returns text assigned to <paramref name="key"/> from <see cref="Manager"/>
/// </summary>
public static string GetText(string key) => Manager.GetTextValue(key)?.Value;
```
For example, the following code is used by Localized Components in runtime:
```C#
//This code always returns null or empty string in Edit time because the Manager initialized only in Runtime/Play Mode
KnotLocalization.GetText("key");
```

But you can access Database data from both Edit and Play Mode times. For example:

```C#
foreach (var databaseLanguage in KnotLocalization.ProjectSettings.DefaultDatabase.Languages)
    Debug.Log(databaseLanguage.CultureName);
```

**Comment by mrkyee** [comment]
That's really a pity. If there was a way to support editing to display data such as Lean Localization
 [https://assetstore.unity.com/packages/tools/localization/lean-localization-28504 ](url) , then it would be the perfect solution

**Comment by V0odo0** [comment]
> That's really a pity. If there was a way to support editing to display data such as Lean Localization [https://assetstore.unity.com/packages/tools/localization/lean-localization-28504 ](url) , then it would be the perfect solution

If I understand you correctly, you would like to see the the actual text behind selected key right on the text component in Edit time?

If that so, I don't think it is good idea to modify the targets of localized component without user permission in Edit time. Doing this from code automatically there might be performance issues, unwanted component modifications & prefab overrides.

If you want to see how your text for the specific languages will look on your component you can always copy-paste it from Database Editor. Or copy-paste the key itself and leave it your text component as placeholder.

![image](https://user-images.githubusercontent.com/10213769/236236413-859fd69a-0f6e-4176-a739-abba5e2d56ae.png)

**Comment by mrkyee** [comment]
Yes, I want to be able to view the actual values of the corresponding language while in edit mode and be able to switch languages. If I need to copy from the database, then I have to do it manually one by one, which takes time.

**Comment by V0odo0** [comment]
> Yes, I want to be able to view the actual values of the corresponding language while in edit mode and be able to switch languages. If I need to copy from the database, then I have to do it manually one by one, which takes time.

Agreed. The workaround I see is to add context-menu or button that applies the text from specific language immediatly in Edit time. Will add it to my todo-list. Thank you.

**Comment by mrkyee** [comment]
By the way, I have two usage-related questions. 
1. Do you know how to localize an item database? For example, item names and descriptions. Currently, I am storing item data using a ScriptableObject. Do I need to add all items to the localization database and then use the getText method to retrieve the corresponding values? This seems like a lot of work, and if I delete or modify my item ScriptableObject file, it could lead to inconsistencies with the data in the localization database. 
2. How can I better manage a growing localization database?
