### ISSUE TITLE
[Question] Creating Custom KnotManager script

### ISSUE THREAD

**Issue by Debjoy** [V0odo0/KNOT-Localization#3]
Hi, I wanted to create a custom KnotManager class with modified existing functions like LoadLanguageAsync, AppendMissingKeys, etc. 
I have made changes to original KnotManager file, which is doing its purpose, but is there a better way to create a custom class file without touching original file?

**Comment by V0odo0** [comment]
You can create your own manager class by implementing IKnotManager interface.

```C#
public class MyCustomManager : IKnotManager
{
    private readonly KnotManager _managerBase = new KnotManager();

    public void Dispose()
    {
        _managerBase.Dispose();
    }

    public void SetDatabase(KnotDatabase database, bool loadStartupLanguage = false)
    {
        _managerBase.SetDatabase(database, loadStartupLanguage);
    }

    public void LoadLanguage(KnotLanguageData languageData)
    {
        //Do my stuff
    }

    //...
}
```

Then you can override default type of manager implementation in project settings.

![image](https://github.com/V0odo0/KNOT-Localization/assets/10213769/92b47203-697a-40b3-8bf2-c96027632f74)

**Comment by Debjoy** [comment]
Thank you very much. this helps.
