### ISSUE TITLE
[Feature] Hierarchy Tree Folder per Text Collection

### ISSUE THREAD

**Issue by digiwombat** [V0odo0/KNOT-Localization#5]
Hey!

Firstly, thanks for your hard work on this project.

Secondly, it'd be nice to have a foldout/folder in the hierarchy tree per text collection.

In my case, I have a few collections (UI and LockMessages) and it would be nice just to have the separation to make my list a bit cleaner without having to prepend it to the key.

**Comment by V0odo0** [comment]
> Hey!
> 
> Firstly, thanks for your hard work on this project.
> 
> Secondly, it'd be nice to have a foldout/folder in the hierarchy tree per text collection.
> 
> In my case, I have a few collections (UI and LockMessages) and it would be nice just to have the separation to make my list a bit cleaner without having to prepend it to the key.

Hi. I don't think this would be a good idea since you'll get a foldout for each text collection assigned to each language. Having multiple languages, the hierarchy tree will be flooded with key duplicates as a result.

Is your UI and LockMessages text collections was imported from external sources?
