### ISSUE TITLE
Import Export: No way to create a text asset in editor?

### ISSUE THREAD

**Issue by Snownee** [V0odo0/KNOT-Localization#6]
First of all, thank you for making this tool.

However, I think the Addons section in the wiki lacks some necessary information. After some fiddling, I can now make it work properly. It's a little awkward that I have to create a .txt file in the system explorer because I couldn't find the option to create a text asset in Unity 6's “Create” menu. I'm not sure if this is a known situation, so I thought it best to let you know about it.

**Comment by V0odo0** [comment]
Thank you!

Text asset is not a Unity specific format and can have other extensions like csv, json, txt. So yes, you need to create the text asset yourself.
